educacionavanzada-master/EducacionAvanzada/EducacionAvanzada.WebAdmin/Controllers/NotasController.cs
using EducacionAvanzada.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducacionAvanzada.WebAdmin.Controllers
{
    [Authorize]
    public class NotasController : Controller
    {
        NotasBL _notasBL;
        AlumnosBL _alumnosBL;
        GradosBL _gradosBL;
        JornadasBL _jornadasBL;
        seccionBL _seccionesBL;

        public NotasController()
        {
            _notasBL = new NotasBL();
            _alumnosBL = new AlumnosBL();
            _gradosBL = new GradosBL();
            _jornadasBL = new JornadasBL();
            _seccionesBL = new seccionBL();
        }
        // GET: Notas
        public ActionResult Index()
        {
            var listadeNotas = _notasBL.ObtenerNotas();

            return View(listadeNotas);
        }


        public ActionResult Crear()
        {
            var nuevaNota = new Notas();
            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();
            


            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");


            return View(nuevaNota);
        }

        [HttpPost]
        public ActionResult Crear(Notas nota)
        {

            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();


            if (ModelState.IsValid)
            {
                if (nota.GradoId == 0 || nota.JornadaId == 0 || nota.SeccionId == 0)
                {
                    if (nota.GradoId == 0)
                    {
                        ModelState.AddModelError("Grado", "Seleccione un grado");
                    }

                    if (nota.JornadaId == 0)
                    {
                        ModelState.AddModelError("Jornada", "Seleccione una Jornada");
                    }

                    if (nota.SeccionId == 0)
                    {
                        ModelState.AddModelError("seccion", "Seleccione una Sección");
                    }

                    ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
                    ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
                    ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

                    return View(nota);
                }

                //Validacion del año
                var anioActual = Convert.ToInt32((DateTime.Now).Year);
                if (nota.Anio != anioActual)
                {
                    ModelState.AddModelError("Anio", "Ingrese el año correcto");

                    ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
                    ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
                    ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

                    return View(nota);
                }

                _notasBL.GuardarNota(nota);

                return RedirectToAction("Index");
            }

           // var alumnos = _alumnosBL.ObtenerAlumnosactivo();

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

            return View(nota);
        }

        public ActionResult Editar(int id)
        {
            var nota = _notasBL.ObtenerNota(id);
            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();
            var alumnos = _alumnosBL.ObtenerAlumnosactivo();

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion", nota.GradoId);
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion", nota.JornadaId);
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion", nota.SeccionId);

            return View(nota);
        }

        [HttpPost]
        public ActionResult Editar(Notas nota)
        {
            var grados = _gradosBL.ObtenerGrados();
            var jornadas = _jornadasBL.ObtenerJornadas();
            var secciones = _seccionesBL.ObtenerSecciones();
           

            if (ModelState.IsValid)
            {
                

                if (nota.GradoId == 0 || nota.JornadaId == 0)
                {
                    if (nota.GradoId == 0)
                    {
                        ModelState.AddModelError("Grado", "Seleccione un grado");
                    }

                    if (nota.JornadaId == 0)
                    {
                        ModelState.AddModelError("Jornada", "Seleccione una Jornada");
                    }

                    ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
                    ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
                    ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");

                    return View(nota);
                }

                _notasBL.GuardarNota(nota);

                return RedirectToAction("Index");
            }

            ViewBag.GradoId = new SelectList(grados, "Id", "Descripcion");
            ViewBag.JornadaId = new SelectList(jornadas, "Id", "Descripcion");
            ViewBag.SeccionId = new SelectList(secciones, "Id", "Descripcion");
            return View(nota);
        }

        public ActionResult Detalle(int id)
        {
            var nota = _notasBL.ObtenerNota(id);

            return View(nota);
        }

    }
}

educacionavanzada-master/EducacionAvanzada/EducacionAvanzada.WebAdmin/Controllers/NotasDetalleController.cs
using EducacionAvanzada.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducacionAvanzada.WebAdmin.Controllers
{
    [Authorize]
    public class NotasDetalleController : Controller

    {
        NotasBL _notaBL;
        AlumnosBL _alumnosBL;
        materiaBL _MateriaBL;
        

        public NotasDetalleController()
        {
            _notaBL = new NotasBL();
            _alumnosBL = new AlumnosBL();
            _MateriaBL = new materiaBL();
        }
        // GET: NotasDetalle
        public ActionResult Index(int id)
        {
            var Notas = _notaBL.ObtenerNota(id);
            Notas.ListadeNotasDetalle = _notaBL.ObtenerNotasDetalle(id);
            return View(Notas);
        }

        public ActionResult Crear(int id)   
        {
            var nuevaNotasDetalle = new NotasDetalle();
            nuevaNotasDetalle.NotaId = id;

            var alumnos = _alumnosBL.ObtenerAlumnosactivo();
            ViewBag.AlumnoId = new SelectList(alumnos, "Id", "Nombre");

            var materias = _MateriaBL.Obtenermaterias();
            ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion");

            return View(nuevaNotasDetalle);
        }

        [HttpPost]
        public ActionResult Crear(NotasDetalle notasDetalle)
        {
            if(ModelState.IsValid)
            {
                if(notasDetalle.AlumnoId == 0)
                {
                    ModelState.AddModelError("AlumnoId", "Seleccione un Alumno");
                    return View(notasDetalle);
                }

                _notaBL.GuardarNotasDetalle(notasDetalle);
                return RedirectToAction("Index", new { id = notasDetalle.NotaId });
            }
            var alumnos = _alumnosBL.ObtenerAlumnosactivo();
            ViewBag.AlumnoId = new SelectList(alumnos, "Id", "Nombre");

            return View(notasDetalle);
        }

        public ActionResult Editar(int Id)
        {
            var notaDetalle = _notaBL.ObtenerNotasDetalleporId(Id);
            var alumnos = _alumnosBL.ObtenerAlumnos();
            var materias = _MateriaBL.Obtenermaterias();


            ViewBag.AlumnoId = new SelectList(alumnos, "Id", "Nombre", notaDetalle.AlumnoId);
            ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion", notaDetalle.MateriaId);
          


            return View(notaDetalle);
        }

        [HttpPost]
        public ActionResult Editar(NotasDetalle notaDetalle)
        {
            var alumnos = _alumnosBL.ObtenerAlumnosactivo();
            var materias = _MateriaBL.Obtenermaterias();

            if (ModelState.IsValid)
            {


                if (notaDetalle.AlumnoId == 0 || notaDetalle.MateriaId == 0)
                {
                    if (notaDetalle.AlumnoId == 0)
                    {
                        ModelState.AddModelError("Alumno", "Seleccione un Alumno");
                    }

                    if (notaDetalle.MateriaId == 0)
                    {
                        ModelState.AddModelError("Materia", "Seleccione una Materia");
                    }

                    ViewBag.AlumnoId = new SelectList(alumnos, "Id", "Nombre");
                    ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion");

                    return View(notaDetalle);
                }

                _notaBL.GuardarNotasDetalle(notaDetalle, true);

                return RedirectToAction("Index",new { id = notaDetalle.NotaId });
            }

            ViewBag.AlumnoId = new SelectList(alumnos, "Id", "Nombre");
            ViewBag.MateriaId = new SelectList(materias, "Id", "Descripcion");
            return View(notaDetalle);
        }



        public ActionResult Eliminar(int id)
        {
            var notaDetalle = _notaBL.ObtenerNotasDetalleporId(id);

            return View(notaDetalle);
        }
        [HttpPost]
        public ActionResult Eliminar(NotasDetalle notaDetalle)
        {
            _notaBL.EliminarNotaDetalle(notaDetalle.Id);
            return RedirectToAction("Index", new { id = notaDetalle.NotaId });
        }
    }
    
}

educacionavanzada-master/EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/Notas/Crear.cshtml
@model EducacionAvanzada.BL.Notas

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Notas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Grado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Grado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Jornada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("JornadaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Jornada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.seccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SeccionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.seccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a Notas", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

educacionavanzada-master/EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/Notas/Detalle.cshtml
@model EducacionAvanzada.BL.Notas

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Notas</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Grado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grado.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Jornada.Descripcion)
        </dd>

        <dt>
            Sección
        </dt>

        <dd>
            @Html.DisplayFor(model => model.seccion.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anio)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }) |
    @Html.ActionLink("Regresar a Notas", "Index")
</p>

educacionavanzada-master/EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/Notas/Editar.cshtml
@model EducacionAvanzada.BL.Notas

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Notas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Grado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GradoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GradoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Jornada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("JornadaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.JornadaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.seccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SeccionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SeccionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a Notas", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

educacionavanzada-master/EducacionAvanzada/EducacionAvanzada.WebAdmin/Views/Notas/Index.cshtml
@model IEnumerable<EducacionAvanzada.BL.Notas>

@{
    ViewBag.Title = "Notas";
}

<h2>Notas</h2>

<p>
    @Html.ActionLink("Nueva Nota", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Grado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Jornada)
        </th>
        <th>
            Sección
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Anio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Grado.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Jornada.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.seccion.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Anio)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Id }) |
            @Html.ActionLink("Detalle", "Detalle", new { id=item.Id }) |
            @Html.ActionLink("Ver Alumnos", "Index", "NotasDetalle", new { id=item.Id }, null)
        </td>
    </tr>
}

</table>